// ============================================================
// PPTX Export — uses pptxgenjs loaded from CDN via script tag
// The library is NOT installed via npm (too large, causes Vite
// chunking issues). Instead we inject the CDN script once and
// access it through window.PptxGenJS.
// CDN tag is injected into index.html OR loaded on-demand here.
// ============================================================

import type { GeneratedPPT } from '@/hooks/usePPTGenerator';
import type { GeneratedSlide } from '@/types/database';

type DesignTheme = 'modern' | 'minimal' | 'corporate';

interface ThemeConfig {
  bg: string;
  titleColor: string;
  textColor: string;
  accentColor: string;
  fontTitle: string;
  fontBody: string;
}

const THEMES: Record<DesignTheme, ThemeConfig> = {
  modern: {
    bg: '0F0F1A',
    titleColor: 'A78BFA',
    textColor: 'E2E8F0',
    accentColor: '7C3AED',
    fontTitle: 'Calibri',
    fontBody: 'Calibri',
  },
  minimal: {
    bg: 'FFFFFF',
    titleColor: '1E293B',
    textColor: '475569',
    accentColor: '7C3AED',
    fontTitle: 'Calibri',
    fontBody: 'Calibri',
  },
  corporate: {
    bg: 'F8FAFC',
    titleColor: '0F172A',
    textColor: '334155',
    accentColor: '2563EB',
    fontTitle: 'Calibri',
    fontBody: 'Calibri',
  },
};

// ── CDN loader ────────────────────────────────────────────────
// Injects pptxgenjs bundle script tag once; resolves when ready.
const CDN_URL = 'https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/libs/pptxgen.bundle.js';

let loadPromise: Promise<void> | null = null;

function loadPptxGenJS(): Promise<void> {
  if (loadPromise) return loadPromise;

  // Already loaded by a previous call or by index.html
  if (typeof (window as any).PptxGenJS !== 'undefined') {
    loadPromise = Promise.resolve();
    return loadPromise;
  }

  loadPromise = new Promise<void>((resolve, reject) => {
    const script = document.createElement('script');
    script.src = CDN_URL;
    script.async = true;
    script.onload = () => resolve();
    script.onerror = () => reject(new Error('Failed to load pptxgenjs from CDN. Check your internet connection.'));
    document.head.appendChild(script);
  });

  return loadPromise;
}

// ── Main export function ──────────────────────────────────────
// Accepts the GeneratedPPT shape directly — no DbPPT needed.
export async function exportToPPTX(ppt: GeneratedPPT & { topic?: string }): Promise<void> {
  await loadPptxGenJS();

  const PptxGenJS = (window as any).PptxGenJS;
  if (!PptxGenJS) throw new Error('PptxGenJS not available after load.');

  const pres = new PptxGenJS();
  const themeKey = (ppt.design_theme ?? 'modern') as DesignTheme;
  const theme: ThemeConfig = THEMES[themeKey] ?? THEMES.modern;

  pres.layout = 'LAYOUT_WIDE';
  pres.author = 'Aura Study';
  pres.company = 'Aura Study';
  pres.title = ppt.title;

  // ── Cover slide ──────────────────────────────────────────────
  const cover = pres.addSlide();
  cover.background = { color: theme.bg };

  // Background gradient rect (decorative)
  cover.addShape(pres.ShapeType.rect, {
    x: 0, y: 4.5, w: '100%', h: 1.0,
    fill: { color: theme.accentColor, transparency: 92 },
    line: { color: theme.accentColor, transparency: 92 },
  });

  cover.addText(ppt.title, {
    x: 0.6, y: 1.8, w: '88%', h: 1.8,
    fontSize: 38, bold: true,
    color: theme.titleColor,
    fontFace: theme.fontTitle,
    align: 'center',
    breakLine: true,
  });
  cover.addText('Generated by Aura Study', {
    x: 0.6, y: 3.8, w: '88%', h: 0.4,
    fontSize: 12, color: theme.textColor,
    fontFace: theme.fontBody,
    align: 'center',
  });
  // Accent underline
  cover.addShape(pres.ShapeType.rect, {
    x: 3.5, y: 3.6, w: 3, h: 0.04,
    fill: { color: theme.accentColor },
    line: { color: theme.accentColor },
  });

  // ── Content slides ────────────────────────────────────────────
  ppt.slides.forEach((slide: GeneratedSlide, idx: number) => {
    const s = pres.addSlide();
    s.background = { color: theme.bg };

    // Slide number (bottom-right)
    s.addText(`${idx + 1} / ${ppt.slides.length}`, {
      x: 8.8, y: 5.1, w: 1.0, h: 0.3,
      fontSize: 9, color: theme.textColor,
      fontFace: theme.fontBody,
      align: 'right',
    });

    // Title
    s.addText(slide.title, {
      x: 0.5, y: 0.3, w: '90%', h: 0.85,
      fontSize: 24, bold: true,
      color: theme.titleColor,
      fontFace: theme.fontTitle,
    });

    // Accent underline bar
    s.addShape(pres.ShapeType.rect, {
      x: 0.5, y: 1.12, w: 1.0, h: 0.035,
      fill: { color: theme.accentColor },
      line: { color: theme.accentColor },
    });

    // Subtitle (italic, below title)
    let contentY = 1.3;
    if (slide.subtitle) {
      s.addText(slide.subtitle, {
        x: 0.5, y: contentY, w: '90%', h: 0.4,
        fontSize: 13, color: theme.textColor,
        fontFace: theme.fontBody,
        italic: true,
      });
      contentY += 0.45;
    }

    // Bullet points
    const bullets = slide.content.map((point: string) => ({
      text: point,
      options: {
        bullet: { type: 'bullet' as const },
        fontSize: 15,
        color: theme.textColor,
        fontFace: theme.fontBody,
        paraSpaceAfter: 5,
      },
    }));

    if (bullets.length) {
      const bulletH = Math.min(bullets.length * 0.55 + 0.2, 3.2);
      s.addText(bullets, {
        x: 0.5, y: contentY, w: '90%', h: bulletH,
        valign: 'top',
      });
    }

    // Visual suggestion note (bottom-left, subtle)
    if (slide.visual_suggestion) {
      s.addText(`⭐ Visual: ${slide.visual_suggestion}`, {
        x: 0.5, y: 5.0, w: 7.5, h: 0.3,
        fontSize: 9, color: theme.accentColor,
        fontFace: theme.fontBody,
        italic: true,
      });
    }

    // Speaker notes (native PPTX notes panel)
    if (slide.speaker_notes) {
      s.addNotes(slide.speaker_notes);
    }
  });

  const safeTitle = ppt.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  await pres.writeFile({ fileName: `${safeTitle}_aura_study.pptx` });
}
