// ============================================================
// PPTX Export using pptxgenjs (loaded from CDN via window)
// ============================================================
// Install: npm install pptxgenjs
// Or add to index.html: <script src="https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/libs/pptxgen.bundle.js"></script>

import type { Slide, DbPPT } from '@/types/database';

interface ThemeConfig {
  bg: string;
  titleColor: string;
  textColor: string;
  accentColor: string;
  fontTitle: string;
  fontBody: string;
}

const THEMES: Record<string, ThemeConfig> = {
  modern: {
    bg: '0F0F1A',
    titleColor: 'A78BFA',
    textColor: 'E2E8F0',
    accentColor: '7C3AED',
    fontTitle: 'Calibri',
    fontBody: 'Calibri',
  },
  minimal: {
    bg: 'FFFFFF',
    titleColor: '1E293B',
    textColor: '475569',
    accentColor: '7C3AED',
    fontTitle: 'Calibri',
    fontBody: 'Calibri',
  },
  corporate: {
    bg: 'F8FAFC',
    titleColor: '0F172A',
    textColor: '334155',
    accentColor: '2563EB',
    fontTitle: 'Calibri',
    fontBody: 'Calibri',
  },
};

export async function exportToPPTX(ppt: DbPPT): Promise<void> {
  // Dynamic import — works if pptxgenjs is installed via npm
  const PptxGenJS = (await import('pptxgenjs')).default;
  const pres = new PptxGenJS();

  const theme = THEMES[(ppt as any).design_theme ?? 'modern'] ?? THEMES.modern;

  pres.layout = 'LAYOUT_WIDE';
  pres.author = 'Aura Study';
  pres.company = 'Aura Study';
  pres.title = ppt.topic;

  // Title slide
  const titleSlide = pres.addSlide();
  titleSlide.background = { color: theme.bg };
  titleSlide.addText(ppt.topic, {
    x: 0.5, y: 2.5, w: '90%', h: 1.5,
    fontSize: 40, bold: true,
    color: theme.titleColor,
    fontFace: theme.fontTitle,
    align: 'center',
  });
  titleSlide.addText('Generated by Aura Study', {
    x: 0.5, y: 4.2, w: '90%', h: 0.5,
    fontSize: 14, color: theme.textColor,
    fontFace: theme.fontBody, align: 'center',
  });
  // Accent bar
  titleSlide.addShape(pres.ShapeType.rect, {
    x: 3, y: 4.8, w: 4, h: 0.05,
    fill: { color: theme.accentColor },
    line: { color: theme.accentColor },
  });

  // Content slides
  (ppt.slides as Slide[]).forEach((slide, idx) => {
    const s = pres.addSlide();
    s.background = { color: theme.bg };

    // Slide number
    s.addText(`${idx + 1} / ${ppt.slides.length}`, {
      x: 8.8, y: 5.1, w: 1, h: 0.3,
      fontSize: 10, color: theme.textColor,
      fontFace: theme.fontBody, align: 'right',
    });

    // Title
    s.addText(slide.title, {
      x: 0.5, y: 0.3, w: '90%', h: 0.9,
      fontSize: 26, bold: true,
      color: theme.titleColor,
      fontFace: theme.fontTitle,
    });

    // Accent underline
    s.addShape(pres.ShapeType.rect, {
      x: 0.5, y: 1.15, w: 1.2, h: 0.04,
      fill: { color: theme.accentColor },
      line: { color: theme.accentColor },
    });

    // Subtitle if present
    if ((slide as any).subtitle) {
      s.addText((slide as any).subtitle, {
        x: 0.5, y: 1.25, w: '90%', h: 0.45,
        fontSize: 14, color: theme.textColor,
        fontFace: theme.fontBody, italic: true,
      });
    }

    // Bullet points
    const bullets = slide.content.map(point => ({
      text: point,
      options: { bullet: { type: 'bullet' as const }, fontSize: 16, color: theme.textColor, fontFace: theme.fontBody, paraSpaceAfter: 6 },
    }));
    if (bullets.length) {
      s.addText(bullets, {
        x: 0.5, y: 1.8, w: '90%', h: 3.0,
        valign: 'top',
      });
    }

    // Visual suggestion note (bottom)
    if ((slide as any).visual_suggestion) {
      s.addText(`💡 ${(slide as any).visual_suggestion}`, {
        x: 0.5, y: 5.0, w: '90%', h: 0.3,
        fontSize: 10, color: theme.accentColor,
        fontFace: theme.fontBody, italic: true,
      });
    }

    // Speaker notes
    if ((slide as any).speaker_notes) {
      s.addNotes((slide as any).speaker_notes);
    }
  });

  const safeTitle = ppt.topic.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  await pres.writeFile({ fileName: `${safeTitle}_aura_study.pptx` });
}
